name: Version Bump and Publish

on:
  push:
    branches:
      - master
      - main
    # Don't trigger on README updates or documentation changes
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/**'

jobs:
  version-bump-and-publish:
    runs-on: ubuntu-latest
    # Prevent this from running when it's a release commit
    if: "!contains(github.event.head_commit.message, 'chore(release):')"
    
    # We need write permission for pull requests
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      # Check out the repository - uses the GITHUB_TOKEN automatically provided by GitHub Actions
      # This token has limited permissions and expires after the workflow run completes
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for tags
          token: ${{ secrets.GITHUB_TOKEN }}  # Using the built-in token for checkout
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      # Configure Git identity for the version bump commit
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      # Create a new branch for the version bump
      - name: Create version bump branch
        run: |
          BRANCH_NAME="version-bump-$(date +%s)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME
      
      # Bump version and create a commit with the new version
      - name: Bump version
        run: |
          npm version patch -m "chore(release): bump version to %s"
          VERSION=$(node -p "require('./package.json').version")
          echo "Bumped version to $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      # Push the version bump branch
      - name: Push version bump branch
        run: |
          git push origin $BRANCH_NAME
          
      # Create a PR for the version bump
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(release): bump version to ${{ env.VERSION }}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: ${{ env.BRANCH_NAME }}
          base: master
          delete-branch: true
          title: "chore(release): bump version to ${{ env.VERSION }}"
          body: |
            Automated version bump via GitHub Actions
            
            This PR bumps the version to ${{ env.VERSION }} for release.
          labels: |
            automated
            version-bump
      
      # Auto-merge the pull request if possible
      - name: Auto-merge PR
        run: gh pr merge --auto --squash "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.cpr.outputs.pull-request-number
        
      # Publish to npm using the NPM_TOKEN secret
      # Note: We're publishing from the version bump branch
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      # Create a GitHub release based on the new tag
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 